### ISSUE TITLE
Insufficient permissions on Android 6

### ISSUE THREAD

**Issue by alumae** [Kaljurand/K6nele#43]
When I try to use K6nele as a keyboard to dictate to a text field, I get the "[ insufficient permissions ]" error, reported on top of the yellow mic button, after I tap the button to dictate.

Nexus 5X, Android 6.0.1

**Comment by Kaljurand** [comment]
This error indicates that Kõnele does not have the "microphone permission". The easiest way to add it is to click on Kõnele's launcher icon, then on the yellow microphone button, and finally on "Allow" (on the permissions asking dialog that pops up). I expect that most users go through this right after installing the app, that's why there is no separate permissions dialog for the IME.

Note that if you use 3rd party recognition services via Kõnele's UI, then these services need to be given permissions separately, via their own UI.

Permissions asking is difficult to get right. The current UX is definitely not ideal. Thus keeping the issue open.

**Comment by alumae** [comment]
Yes, the the given steps work but experienced users might not ever use K6nele via launcker.

We have to investigate how other keywords have solved this.

**Comment by Kaljurand** [comment]
Regarding the other keyboards: Swype pops up the standard permissions asking dialog, Google Keyboard (SwiftKey, etc.) fail with a vague message (attached).

![googlekeyboard](https://cloud.githubusercontent.com/assets/490600/14087196/089b81e8-f529-11e5-9f84-f48c6edc6345.png)

**Comment by Kaljurand** [comment]
Should be fixed in b39b5a30ee6c0c7813ae06c5062038341f164423 (v1.5.18). Please verify.
