### ISSUE TITLE
[FR] Web Speech API

### ISSUE THREAD

**Issue by ildar** [Kaljurand/K6nele#79]
is it possible to add Web Speech API backend? That could widen the supported language list a lot. 

Demo's available on the page "Web Speech API Demonstration" held by Google.

**Comment by Kaljurand** [comment]
I think support for different backends is out of scope for Kõnele, which is more of a user interface project. In case you want to implement an Android service yourself that is accessible from Kõnele, then follow the links in the selected answer in https://github.com/Kaljurand/K6nele/discussions/38.

Note that Google's Android recognizer can be already used from Kõnele, simply because it comes with the standard Android speech recognizer interface. It offers a similar language coverage than the "Web Speech API Demonstration", and is perhaps based on the same backend. So perhaps this already satisfies your request.

However, support for the API constants and functions listed in the Web Speech API draft (https://wicg.github.io/speech-api/), e.g. as a mapping to Android intents/extras would be in the scope for Kõnele, but it's low priority for now, and it's probably not what you're after.
